apiVersion: v1
kind: Pod
metadata:
  name: php
spec:
  containers:
    - name: php
      image: php-mysql-demo:1.0.0
      imagePullPolicy: Never
      resources:
        limits:
          memory: "500Mi"
